name: Build and Deploy (Stage)

on:
  push:
    branches:
      - '**'
    tags:
      - 'stage-*'

jobs:
  build:
    name: Build and Push ARM64 Docker Image to ECR
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Fetch environment variables from SSM
        run: |
          PARAM_PREFIX="/mercantile/stage"
          for VAR in VITE_USER_EMAIL_TEMPLATE VITE_EMAIL_USER_ID VITE_EMAIL_TEMPLATE VITE_EMAIL_SERVICE_ID VITE_SUPABASE_API_KEY VITE_SUPABASE_URL ECR_REPOSITORY; do
            VALUE=$(aws ssm get-parameter --name "$PARAM_PREFIX/$VAR" --with-decryption --query "Parameter.Value" --output text)
            echo "$VAR=$VALUE" >> $GITHUB_ENV
            echo "$VAR=$VALUE" >> .env
          done

      - name: Set image tag to commit hash
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

      - name: Build and push ARM64 Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg VITE_USER_EMAIL_TEMPLATE=$VITE_USER_EMAIL_TEMPLATE \
            --build-arg VITE_EMAIL_USER_ID=$VITE_EMAIL_USER_ID \
            --build-arg VITE_EMAIL_TEMPLATE=$VITE_EMAIL_TEMPLATE \
            --build-arg VITE_EMAIL_SERVICE_ID=$VITE_EMAIL_SERVICE_ID \
            --build-arg VITE_SUPABASE_API_KEY=$VITE_SUPABASE_API_KEY \
            --build-arg VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
            --tag $ECR_REPOSITORY:latest \
            --tag $ECR_REPOSITORY:$IMAGE_TAG \
            --file Dockerfile.prod \
            --push .

  deploy:
    name: Deploy to ECS (on tag push only)
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    env:
      AWS_REGION: eu-west-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Fetch deployment config from SSM
        run: |
          PARAM_PREFIX="/mercantile/stage"
          for VAR in ECR_REPOSITORY ECS_CLUSTER ECS_SERVICE; do
            VALUE=$(aws ssm get-parameter --name "$PARAM_PREFIX/$VAR" --with-decryption --query "Parameter.Value" --output text)
            echo "$VAR=$VALUE" >> $GITHUB_ENV
          done

      - name: Set image tag to commit hash
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Create imagedefinitions.json
        run: |
          printf '[{"name":"mercantile-staging-container","imageUri":"%s"}]' "$ECR_REPOSITORY:$IMAGE_TAG" > imagedefinitions.json

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: imagedefinitions.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
